### ISSUE TITLE
RoboSmart.discoverAll

### ISSUE THREAD

**Issue by f15radar** [sandeepmistry/node-robosmart#2]
When I use this function, it hangs.  Can you give me an example of how to use this?

**Comment by sandeepmistry** [comment]
@f15radar please see: https://github.com/sandeepmistry/node-robosmart/blob/master/test.js#L5

If you still have issues, please provide debug output:

OS X

```
DEBUG=* node test.js
```

Linux:

```
sudo DEBUG=* node test.js
```

**Comment by f15radar** [comment]
I did finally get it to stop hanging.  I wasn't calling callback.  But even though I can get the results of DiscoverAll.  I cant seem to do anything with it.  For example I do:

var async = require('async');
var RoboSmart = require('./index');
var found =0;
// print process.argv
process.argv.forEach(function (val, index, array) {
  console.log(index + ': ' + val);
});
RoboSmart.discoverAll(2000,function(devices) {
  async.series([
  function(callback) {
  console.log(devices[0]);
  callback();
  },
    function(callback) {
    var roboSmart = devices[0];
    roboSmart.getLightName(function(lightName) {
    console.log('light name = ' + lightName);
    if(lightName = 'XXXX'){
    found=1;
    console.log(found);
    }
    callback();
  });
},
],
function() {
process.exit(0);
});
}
);

I get this:

0: node
1: /home/pi/node_modules/robosmart/mytest2.js
{ _peripheral:
   { _noble:
      { state: 'poweredOn',
        _bindings: [Object],
        _peripherals: [Object],
        _services: [Object],
        _characteristics: [Object],
        _descriptors: [Object],
        _discoveredPeripheralUUids: [Object],
        _events: [Object],
        _allowDuplicates: undefined },
     id: 'xxxx',
     uuid: 'xxxxxxxxxxxxx',
     address: 'xxxxxxxxxx',
     addressType: 'public',
     connectable: true,
     advertisement:
      { localName: 'xxxx\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000',
        txPowerLevel: 4,
        manufacturerData: <Buffer 31 46 46>,
        serviceData: [],
        serviceUuids: [Object] },
     rssi: -73,
     services: null,
     state: 'disconnected' },
  _publicService: null,
  _characteristics: {} }
/home/pi/node_modules/robosmart/index.js:80
  this._characteristics[uuid].read(function(error, data) {
                             ^
TypeError: Cannot read property 'read' of undefined
    at Robosmart.readCharacteristic (/home/pi/node_modules/robosmart/index.js:80:30)
    at Robosmart.readStringCharacteristic (/home/pi/node_modules/robosmart/index.js:120:8)
    at Robosmart.getLightName (/home/pi/node_modules/robosmart/index.js:130:8)
    at /home/pi/node_modules/robosmart/mytest2.js:16:15
    at /home/pi/node_modules/async/lib/async.js:713:13
    at Immediate.iterate [as _onImmediate](/home/pi/node_modules/async/lib/async.js:262:13)
    at processImmediate [as _immediateCallback](timers.js:367:17)

Any help would be appreciated.

**Comment by f15radar** [comment]
Sorry didn't mean to close

**Comment by sandeepmistry** [comment]
@f15radar you'll need to call `discoverServicesAndCharacteristics` after connecting and before `getLightName`.

See here for an example: https://github.com/sandeepmistry/node-robosmart/blob/master/test.js#L11

I'll update the read me to clarify this.
